### ISSUE TITLE
Action reported success even though container pushes failed

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcaflow-container-toolkit-action#1]
## Describe the bug

A carpenter build action for the sysbench plugin experienced a failure condition as reported in https://github.com/arcalot/arcaflow-plugin-image-builder/issues/50, but the Action still reported as passed.

## To reproduce

Unsure how exactly to reproduce, but this instance was related to the failure reported for the image-builder repoi.

## Additional context

Failed action here: https://github.com/arcalot/arcaflow-plugin-sysbench/actions/runs/4416765995/jobs/7741514163#step:6:679

**Comment by BATMAN-JD** [comment]
This was resolved by @mfleader in [PR](https://github.com/arcalot/arcaflow-container-toolkit/pull/51) for the Arcaflow Container Toolkit
